// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {desensitizedTitleField, desensitizedSceneHeading, Transition, Lyric, Note, PB, Action} from "./tokenizer"
export const parser = LRParser.deserialize({
  version: 14,
  states: "&`OQOPOOOOOO'#Ci'#CiO`OPO'#CcOnOQO'#CjOvOPO'#CcQ!ROPOOOOOO-E6g-E6gO!WOPO,58}OOOO'#Ck'#CkO!cOQO,59UO!kOPO,59UOOOO-E6h-E6hO!nOPO'#CeO#UOPO'#ClQ!ROPOOOOOO-E6i-E6iO#`OPO1G.pO#`OPO1G.pO#hOPO1G.pO#mOQO,59PO#xOQO'#CgO$QOPO'#CmO$VOPO,59WOOOO-E6j-E6jO$aOPO7+$[O$iOPO7+$[OOOO7+$[7+$[O$nOQO'#CfOOOO1G.k1G.kO$sOPO1G.kOOOO'#Cn'#CnO$xOQO,59ROOOO,59X,59XOOOO-E6k-E6kO%QOPO<<GvOOOO<<Gv<<GvO%VOQO,59QOOOO7+$V7+$VOOOO-E6l-E6lOOOOAN=bAN=bOOOO1G.l1G.l",
  stateData: "%a~OdROfPOcVPeVP~OdROfPOcVXeVX~OgWOhYO~OdROcVXeVX~Oe[O~OdROcVaeVa~OgWOh`O~OWbOgWO~OPeOQeOReOTeOkdO~Oc`Xe`X~P!sOWiOgWO~OfjO~OflOgWOikO~OlnOfZX~OfpO~Oc`ae`a~P!sOWrOgWO~OfsO~OjtO~OfuO~OlnOfZa~OfwO~OixO~OkW[W~",
  goto: "!xcPPPPPPPdPgknPrx!S!f!l!rRTOT]T^RmcTe]fQQORUQQSOQVQTZSVQXRW_XachQaYQc[Rh`Q^TRg^Qf]RqfQodRvo",
  nodeNames: "⚠ Transition Lyric Note PB Action FountainScript TitlePage TContent SceneHeading SceneNumber PageBreak MContent",
  maxTerm: 28,
  skippedNodes: [0,4,12],
  repeatNodeCount: 6,
  tokenData: "'v~RaYZ!W]^!]pq!eqs#]st$St}#]}!O$o!O!P$o!P!Q#]!Q![$o![!]%[!]!_#]!_!`%w!`;'S#];'S;=_#v;=_;=`#|<%l~#]~!]Of~~!bPf~YZ!W~!nUg~WP[PYZ#Q]^#Qp;'S#];'S;=_#v;=_;=`#|<%l~#]P#VQ[PYZ#Q]^#QP#dUWP[PYZ#Q]^#Qp;'S#];'S;=_#v;=_;=`#|<%l~#]P#yP;=`<%l#]P$PP;=`<%k#]R$]UiQWP[PYZ#Q]^#Qp;'S#];'S;=_#v;=_;=`#|<%l~#]R$xUjQWP[PYZ#Q]^#Qp;'S#];'S;=_#v;=_;=`#|<%l~#]R%eUhQWP[PYZ#Q]^#Qp;'S#];'S;=_#v;=_;=`#|<%l~#]R&QWlQWP[PYZ#Q]^#Qp!_#]!_!`&j!`;'S#];'S;=_#v;=_;=`#|<%l~#]P&qWWP[PYZ#Q]^#Qp!_#]!_!`'Z!`;'S#];'S;=_#v;=_;=`#|<%l~#]P'dUkPWP[PYZ#Q]^#Qp;'S#];'S;=_#v;=_;=`#|<%l~#]",
  tokenizers: [0, 1],
  topRules: {"FountainScript":[0,6]},
  specialized: [{term: 8, get: (value, stack) => (desensitizedTitleField(value, stack) << 1)},{term: 8, get: (value, stack) => (desensitizedSceneHeading(value, stack) << 1)},{term: 8, get: (value, stack) => (Transition(value, stack) << 1)},{term: 8, get: (value, stack) => (Lyric(value, stack) << 1)},{term: 12, get: (value, stack) => (Note(value, stack) << 1)},{term: 8, get: (value, stack) => (PB(value, stack) << 1)},{term: 8, get: (value, stack) => (Action(value, stack) << 1)}],
  tokenPrec: 196
})
