// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {desensitizedTitleField, desensitizedSceneHeading, Note, PB, Transition, Lyric, Synopsis} from "./tokenizer"
export const parser = LRParser.deserialize({
  version: 14,
  states: "&SOYQPOOPhOPOOOOQO'#Ci'#CiOmQPO'#CcO{QQO'#CjO!TQPO'#CcQ!`QPOOP!eOPO)C>gOOQO-E6g-E6gO!jQPO,58}OOQO'#Ck'#CkO!uQQO,59UO!}QPO,59UOOQO-E6h-E6hO#QQPO'#CeO#kQPO'#ClQ!`QPOOPOOO/'4R/'4ROOQO-E6i-E6iO#uQPO1G.pO#uQPO1G.pO#}QPO1G.pO$SQPO,59PO$tQPO'#CmOOQO'#Cm'#CmO$yQPO,59WOOQO-E6j-E6jO%TQPO7+$[O%]QPO7+$[OOQO7+$[7+$[O%bQQO'#CfOOQO1G.k1G.kOOQO,59X,59XOOQO-E6k-E6kO%gQPO<<GvOOQO<<Gv<<GvO%lQPO,59QOOQOAN=bAN=bOOQO1G.l1G.l",
  stateData: "%u~OfOSgPQ~OcSOiQObVPdVP~OgVO~OcSOiQObVXdVX~OjYOk[O~OcSObVXdVX~Od^O~OhaO~OcSObVadVa~OjYOkcO~OWeOjYO~OPhOQgORgOSgOThOZgO~Ob`Xd`X~P#VOWlOjYO~OimO~OjYOlnOPXaQXaRXaSXaTXaZXabXadXa~OipO~Ob`ad`a~P#VOWrOjYO~OisO~OmtO~OiuO~OlvO~OWZW~",
  goto: "!mbPPPPPPPcPfjPPms}!a!gRUOT_U`RofQRORWRQTOQXRT]TXQZSWbZdfkQd[Qf^RkcQ`URj`Qi_Rqi",
  nodeNames: "⚠ Note PB Transition Lyric Synopsis FountainScript TitlePage TContent SceneHeading SceneNumber Action Notee",
  maxTerm: 29,
  skippedNodes: [0,12],
  repeatNodeCount: 5,
  tokenData: "-}~RsXY#`YZ#eZ]#`]^#npq$Pqs$yst%nt}$y}!O&X!O!P&X!P!Q$y!Q![&X![!]&r!]!}$y!}#O']#O#y$y#y#z-d#z$f$y$f$g-d$g#BY$y#BY#BZ-d#BZ$IS$y$IS$I_-d$I_$I|$y$I|$JO-d$JO$JT$y$JT$JU-d$JU$KV$y$KV$KW-d$KW&FU$y&FU&FV-d&FV;'S$y;'S;=_%b;=_;=`%h<%l~$y~#eOf~~#nOf~h~i~~#wPf~g~i~YZ#z~$POi~~$YUf~j~WPYZ$l]^$qp;'S$y;'S;=_%b;=_;=`%h<%l~$yP$qOZPP$vPZPYZ$lP%OUWPYZ$l]^$qp;'S$y;'S;=_%b;=_;=`%h<%l~$yP%eP;=`<%l$yP%kP;=`<%k$y~%uUl~WPYZ$l]^$qp;'S$y;'S;=_%b;=_;=`%h<%l~$yR&`UmQWPYZ$l]^$qp;'S$y;'S;=_%b;=_;=`%h<%l~$yR&yUkQWPYZ$l]^$qp;'S$y;'S;=_%b;=_;=`%h<%l~$y~'bWWPYZ$l]^$qp!}$y!}#O'z#O;'S$y;'S;=_%b;=_;=`%h<%l~$y~(PWWPYZ(i]^+Zp#P'z#P#Q+x#Q;'S'z;'S;=_-W;=_;=`-^<%l~'z~(nWZPYZ)W]^)Wp#P)W#P#Q)s#Q;'S)W;'S;=_*};=_;=`+T<%l~)W~)ZWYZ)W]^)Wp#P)W#P#Q)s#Q;'S)W;'S;=_*};=_;=`+T<%l~)W~)vWYZ)W]^)Wp#P)W#P#Q*`#Q;'S)W;'S;=_*};=_;=`+T<%l~)W~*eW[~YZ)W]^)Wp#P)W#P#Q*`#Q;'S)W;'S;=_*};=_;=`+T<%l~)W~+QP;=`<%l)W~+WP;=`<%k)W~+`WZPYZ(i]^)Wp#P)W#P#Q)s#Q;'S)W;'S;=_*};=_;=`+T<%l~)W~+}WWPYZ(i]^+Zp#P'z#P#Q,g#Q;'S'z;'S;=_-W;=_;=`-^<%l~'z~,nW[~WPYZ(i]^+Zp#P'z#P#Q,g#Q;'S'z;'S;=_-W;=_;=`-^<%l~'z~-ZP;=`<%l'z~-aP;=`<%k'z~-kUf~WPYZ$l]^$qp;'S$y;'S;=_%b;=_;=`%h<%l~$y",
  tokenizers: [0, 1],
  topRules: {"FountainScript":[0,6]},
  specialized: [{term: 8, get: (value, stack) => (desensitizedTitleField(value, stack) << 1)},{term: 8, get: (value, stack) => (desensitizedSceneHeading(value, stack) << 1)},{term: 12, get: (value, stack) => (Note(value, stack) << 1)},{term: 8, get: (value, stack) => (PB(value, stack) << 1)},{term: 8, get: (value, stack) => (Transition(value, stack) << 1)},{term: 8, get: (value, stack) => (Lyric(value, stack) << 1)},{term: 8, get: (value, stack) => (Synopsis(value, stack) << 1)}],
  tokenPrec: 217
})
