// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Screenplay = 1,
  TitleField = 2,
  Colon = 4,
  Styled = 6,
  Italic = 7,
  Ast = 8,
  String = 9,
  Char = 10,
  SceneHeading = 11,
  SceneHeadingPrefix = 12,
  int = 13,
  ext = 14,
  est = 15,
  forcedscene = 16
