// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$bOQOPOOOOOO'#Cn'#CnOVOPO'#C_O_OQO'#C^OOOO'#Cm'#CmOgOPOOOOOO-E6l-E6lOOOO'#C`'#C`OOOO,58y,58yOOOO'#Cd'#CdOOOO'#Co'#CoOxOQO'#CeO!WOQO'#CcOOOO'#Cb'#CbOOOO'#Ca'#CaO!]OPO,58xOOOO-E6k-E6kOOOO'#Cl'#ClOOOO'#Ch'#ChO!WOQO'#CgQOOOOOOOOO-E6m-E6mObOPO,58}OOOO1G.d1G.dOOOO,59R,59ROOOO1G.i1G.i",
  stateData: "!e~OePO~OePOfVO~OYYOgXO~O]bO^bO_bOePOiaO~OYYOhXXgXXdXX~OYYO~OhgO~OYY~",
  goto: "!xdPPeimpsvy!PP!Y!]PPP!`!c!i!pTSOTTROTRWQR_RR^RR]RQ[RRifQ^RQf[RhcRdTRcTRbTQTOR`TSQOTRUQUZR[cReZ",
  nodeNames: "⚠ Screenplay TitleField TitleTitle Colon TitleValue Styled Italic Ast String Char SceneHeading SceneHeadingPrefix SceneHeadingPrefix SceneHeadingPrefix SceneHeadingPrefix SceneHeadingPrefix",
  maxTerm: 25,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "%w~RhYZ!mpq!rqz!yz{#O{!O!y!O!P#V!P![!y![!]#^!]!c!y!c!g!r!g!h#e!h!k!r!k!l$v!l!}!r!}#T!y#T#X!r#X#Y#e#Y#]!r#]#^$v#^#o!r#o;'S!y;'S;=_%k;=_;=`%q<%l~!y~!rOh~~!yOYQe~Q#OOYQ~#VOg~YQ~#^Oi~YQR#eOfPYQ~#lSYQe~!u!v#x!z!{$`#g#h#x#l#m$`P#{Q!v!w$R#h#i$RP$WP_P!O!P$ZP$`O_PP$cQ!v!w$i#h#i$iP$nP^P!O!P$qP$vO^P~$}QYQe~!p!q%T#b#c%TP%WQ!v!w%^#h#i%^P%cP]P!O!P%fP%kO]PQ%nP;=`<%l!yQ%tP;=`<%k!y",
  tokenizers: [0, 1],
  topRules: {"Screenplay":[0,1]},
  tokenPrec: 64
})
